### ISSUE TITLE
有没有自动构建 CI 和 发布 详细配置

### ISSUE THREAD

**Issue by Hunlongyu** [Pure-Peace/vue-cli-electron-template#1]
1. 我看了一下有 travis, 那 windows 平台的是手动发布么?
2. 如何同时打包构建 32位 和 64位, 并且添加在软件的后缀上?  如: test-x86-0.1.0.exe, test-x64-0.1.0.exe
3. 如何自动将 构建的软件包 发布到 GitHub release.
4. 如何实现: https://github.com/notable/notable/releases 里发布的那么多软件.

4. 后期有计划 支持 Vue3 和 Ts 么?

**Comment by Hunlongyu** [comment]
我自行尝试了Github 的 Actions .感觉蛮好用的, 自行打包发布.

**Comment by Pure-Peace** [comment]
不好意思，我之前没注意……才看到

GitHub Actions自动打包发布，学到了，感谢
Vue3会支持的，后续等正式版出来了学习一波
