### ISSUE TITLE
electron 打包为啥没有生成latest.yml文件

### ISSUE THREAD

**Issue by liaoweixian** [Pure-Peace/vue-cli-electron-template#3]
electron 打包为啥没有生成latest.yml文件

**Comment by Pure-Peace** [comment]
打包build添加参数publish才能生成latest.yml文件，具体大概是在package.json中加入"release": "vue-cli-service electron:build --publish=always"

**Comment by liaoweixian** [comment]
嗯嗯！ 我知道了，你使用的vue cli 3.0的脚手架， 它的配置方式有一点区别， 已解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Pure-Peace"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月4日(星期六) 晚上11:20
收件人:&nbsp;"Pure-Peace/vue-cli-electron-template"<vue-cli-electron-template@noreply.github.com&gt;;
抄送:&nbsp;"廖不倒i"<965932944@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Pure-Peace/vue-cli-electron-template] electron 打包为啥没有生成latest.yml文件 (#3)





 
打包build添加参数publish才能生成latest.yml文件，具体大概是在package.json中加入"release": "vue-cli-service electron:build --publish=always"

**Comment by Pure-Peace** [comment]
好的，那么关闭issue了
